[workspace]
authors = ["Maxim Zaks <maxim.zaks@gmail.com>", "Daniel Gustaw <gustaw.daniel@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-csv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025072405,<26"
